

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: true

grails:
    controllers:
        upload:
            maxFileSize: 10485760      # 10 MB
            maxRequestSize: 10485760   # 10 MB
spring:
    http:
        multipart:
            max-file-size: 10Mb

# config AWS SDK in external config file
#---
#grails:
#    plugin:
#        awssdk:
#            accessKey:
#            secretKey:

# application specific settings
s3Browse:
    bucketName: dda-de-dev
    deleteAllowed: false  # default to false for read-only safety
    insertAllowed: false  # default to false for read-only safety


